"""
ClipCandidate model — AI-generated clip suggestions from analysis results.

Each clip candidate represents a segment of a video that was identified
as potentially interesting or shareable. Users can accept, reject, or
modify candidates.
"""
from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import JSON

from backend.infrastructure.database.base import Base, UUIDMixin

if TYPE_CHECKING:
    from backend.infrastructure.database.models.caption_track import CaptionTrack
    from backend.infrastructure.database.models.export_job import ExportJob
    from backend.infrastructure.database.models.project_video import ProjectVideo


class ClipCandidate(Base, UUIDMixin):
    """A suggested video clip segment.

    Generated by the AI pipeline from analysis results. Each clip has
    quality, virality, and hook scores. Users interact with clips by
    accepting, rejecting, or modifying them.
    """

    __tablename__ = "clip_candidates"

    # ─── Fields ────────────────────────────────────────────────
    video_id: Mapped[str] = mapped_column(
        String(36),  # type: ignore[name-defined]
        ForeignKey("project_videos.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    start_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    end_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    quality_score: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    virality_score: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    hook_score: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    content_density: Mapped[float | None] = mapped_column(Float, nullable=True, default=None)
    audio_clarity: Mapped[float | None] = mapped_column(Float, nullable=True, default=None)
    visual_variety: Mapped[float | None] = mapped_column(Float, nullable=True, default=None)
    engagement_score: Mapped[float | None] = mapped_column(Float, nullable=True, default=None)
    title: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)
    description: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)
    hashtags: Mapped[list | None] = mapped_column(
        JSON, nullable=True, default=None
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="candidate", index=True
    )
    rank: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    is_favorite: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="0"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=datetime.now(UTC)
    )

    # ─── Relationships ─────────────────────────────────────────
    video: Mapped[ProjectVideo] = relationship("ProjectVideo", back_populates="clip_candidates")
    caption_tracks: Mapped[list[CaptionTrack]] = relationship(
        "CaptionTrack",
        back_populates="clip",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    export_jobs: Mapped[list[ExportJob]] = relationship(
        "ExportJob",
        back_populates="clip",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    # ─── Indexes ───────────────────────────────────────────────
    __table_args__ = (
        Index("idx_clip_video_status", "video_id", "status"),
        Index("idx_clip_video_rank", "video_id", "rank"),
    )
